PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?key ?value WHERE {
  GRAPH ?dg {
    ?
      <http://opencaesar.io/document/tree#includes>
        ?key .
  }
  GRAPH ?vg {
    ?key a ?value
  }
  GRAPH ?cg {
    ?value rdfs:subClassOf <http://opencaesar.io/document/tree#Element>
  }
}